##############################
# Set input and output files #
##############################

# report generated by using "sbt dumpLicenseReport" on
# https://github.com/miraisolutions/spark-bigquery
reportCSV = "spark-bigquery-licenses.csv"
# output README file
outputFile = "java/README"

##############################
library(dplyr)
library(urltools)
library(magrittr)

con <- file(outputFile, "w")

# cat with file = con
cat2file <- function(string) {
  cat(string, file = con)
}

# show a warning if a license string for an artifact gets replaced
licenseWarning <- function (artifact, oldLicense, newLicense) {
  warning(artifact, ": replacing license \"", oldLicense, "\" with license \"", newLicense, "\"")
  newLicense
}

# check if the part in brackets in a license string is a URL with a scheme
# (we want to avoid cases like "../LICENSE.txt" or "LICENSE.txt"
checkLicenseUrl <- function (licenseString) {
  url = sub(".*\\((.+)\\)$", "\\1", licenseString)
  if (is.na(url_parse(url)$scheme)) stop("No valid URL found: ", licenseString)
  url
}

# replace license string for artifacts pointing to local license files
# (or containing no license link at all)
fixLicense <- function(row) {
  switch(row["Title"],
         "Apache HttpClient" = {
           newLicense = "The Apache Software License, Version 2.0 (http://www.apache.org/licenses/LICENSE-2.0.txt)"
           licenseWarning(row["Title"], row["License"], newLicense)
         },
         "Apache Commons Codec" = {
           newLicense = "The Apache Software License, Version 2.0 (http://www.apache.org/licenses/LICENSE-2.0.txt)"
           licenseWarning(row["Title"], row["License"], newLicense)
         },
         "ParaNamer Core" = {
           newLicense = "BSD 3-Clause (https://github.com/paul-hammant/paranamer/blob/master/LICENSE.txt)"
           licenseWarning(row["Title"], row["License"], newLicense)
         },
         "XZ For Java" = {
           newLicense = "Public Domain (https://creativecommons.org/publicdomain/mark/1.0/)"
           licenseWarning(row["Title"], row["License"], newLicense)
         },
         row["License"] %>% checkLicenseUrl)
}


reportDF = read.csv(reportCSV)

# split Notes column according to Unit Separator
separator = "\U001F"
extraCols = data.frame(do.call('rbind', strsplit(as.character(reportDF$Notes), split = separator, fixed = TRUE)))
names(extraCols) = c("Title", "Description", "MainJar", "SourcesJar")
report.df = cbind(reportDF %>% select(-Notes), extraCols)

# drop Scala Library
report.df = report.df[!(report.df$Title == "Scala Library"), ]

intro =
"sparkbq sources can be obtained from GitHub:

- sparkbq R Package: https://github.com/miraisolutions/sparkbq
- spark-bigquery Scala Sources: https://github.com/miraisolutions/spark-bigquery

Due to dependency version mismatches between Apache Spark and Google client
libraries (e.g. Google Guava), the included spark-bigquery fat JAR was built
using shading to relocate relevant Google classes.

The provided fat JAR includes the following open source components:
"

cat2file(intro)
cat2file("\n")

apply(report.df, 1, function(r) {
  cat2file(paste0("- ", r["Title"], "\n"))
  cat2file(paste0("  ", "Description: ", r["Description"], "\n"))
  cat2file(paste0("  ", "License: ", fixLicense(r), "\n"))
  cat2file(paste0("  ", "JAR file: ", r["MainJar"], "\n"))
  cat2file(paste0("  ", "Sources JAR file: ", r["SourcesJar"], "\n"))
  cat2file("\n")
})

cat2file("This list is auto-generated using the SBT sbt-license-report plugin
and using information provided by https://mvnrepository.com/.\n")

close(con)
